### ISSUE TITLE
Settings of the application

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler-tftp#7]
The configuration of the tool should be sourceable in multiple ways:

1. Configuration file
2. Environment variables
3. Daemon flags

The order of this list should be preserved where the first point in the ordered list is the least important one. Thus a value from the environment should be overwritten by the daemon flags.

## Configuration file

The configuration file format should be [YAML](https://yaml.org/spec/1.2.2/).

## Environment variables

The names of the environment variables should be built in the following way: `COBBLER_TFTP_<PARENT_YAML_KEY>_<CHILD_YAML_KEY>_<...>_<KEY_NAME>`

Access to these variables can be achieved with [`os.environ`](https://docs.python.org/3.6/library/os.html#os.environ).

## Daemon flags

The daemon should have the following flag `-c`/`--config` which is used to hand over the location of the configuration file. The default for this is `/etc/cobbler-tftp/settings.yaml`.

The flag for passing settings is the following: `-s`/`--setting`. The value for this flag should have the following format: `<PARENT_YAML_KEY>.<CHILD_YAML_KEY>.<...>.<KEY_NAME>=<VALUE>`. The documentation should state that this flag must thus always be single-quoted and if a single quote appears in the value than it must be escaped. The flag is allowed to be passed multiple times.

Additionally, we will have the following flags of which only one may be present at the same time:

- `--enable-automigration`
- `--disable-automigration`

The library for building the CLI will be [`argparse`](https://docs.python.org/3.6/library/argparse.html).

## Code internal representation

Cobbler should use [`schema`](https://pypi.org/project/schema/) to validate the loaded configuration.

Additional keys should be prohibited. The application should log the names of the keys it didn't accept during startup. The schema of the settings file should be independent of the application and should only contain integers. The settings file should be auto-migrated if desired.

## Settings that should be available for 0.1.0

Default values for the application are present.

```yaml
schema: 1
auto_migrate_settings: false
daemon: true
cobbler:
  uri: "http://localhost/cobbler_api"
  username: "cobbler"
  password: "cobbler"
  password_file: "/etc/cobbler-tftp/cobbler_password"
```

**Comment by ByteOtter** [comment]
So, you set the library for building the CLI as `argparse`. I would like to build a case for using [`click`](https://click.palletsprojects.com/en/8.1.x/).

1. `click` natively [supports our required Python version, 3.6](https://pypi.org/project/click8/) in its most current release. So no digging through the way back machine to find old docs.
2. It's simple. You can think of every command you get in your CLI as kind of an object. Each command can have specific arguments and options it accept via a `@click.argument` and `@click.option` decorators.
Taking a look at the (quite extensive) [documentation](https://click.palletsprojects.com/en/8.1.x/commands/) your whole CLI can essentially be a group of commands.
3. Expanding `cobbler-tftp`'s CLI-functionality should be easier using `click`. We can group click commands in a `group` object and simply add it to the object with `group.add_command(command)`
4. Click can generate help pages. The `--help` flag is a built-in and customizable utility that generates help pages out of the docstrings you give to your commands. Which also more or less forces you to do what we are supposed to do anyways: Document our code.
5. Click can also automatically convert commands and flags to a specific type or check if a given argument is one choice of a list of allowed arguments.

To illustrate my points see this example I took of one of my projects I am currently working on with click: (I changed it a bit to keep it short)
```python
import click

# These settings just rename the standard --help flag to allow for the use of -h and --help
_context_settings = dict(help_option_names=["-h", "--help"])

# This is the group of primary cli commands. It takes the context_settings as arguments
@click.group(context_settings=_context_settings)
def cli():
    """
    Program - Copyright (c) 2023 ByteOtter - Licensed under GPL-v2.0
    Initializing program...
    """
    pass

# This is the create command. It creates the project structure for a given language and project name.
# The language must be within the LANGUAGES list of supported languages. Click filters unsupported languages itself.
# The --git option is set to be a flag with default value FALSE. If true it will run the git init command in the current directory.
@click.command()
@click.argument(
    "language",
    type=click.Choice(utils.LANGUAGES),
    required=1,
    metavar="[LANGUAGE]",
)
@click.argument("projectname", type=click.STRING, required=1)
@click.option(
    "--git", "-g", is_flag=True, default=False, help="Set up git repository aswell."
)
def create(language, projectname, git):
    """
    Create new project structure within current directory.
    LANGUAGE can be either:
    py, c, cpp, cs, java, rb
    PROJECTNAME refers to the name of your project. Your package will be named that way.
    """
# This docstring is being displayed as the help page when calling: `program create --help`

    print(
        # copyright text to be displayed when calling `program create LANGUAGE PROJECTNAME`
    ) 

#
# Logic the command should execute
#
    print(f"Done!")

# The `create` command then needs to be added to the group
cli.add_command(create)

# The logic can be called by simple calling the group object. Click will do the rest.
main():
  cli()

if __name__ == "__main__":
    main()
```

Let me know what you think :)
